title:              Jiyong's Notes
email:              din2346@gmail.com
description:        Deep Learning, Autonomous Driving, Computer Vision
author:             Jiyong Oh
baseurl:            /
url:                "https://IamJiyong.github.io"
production_url:     "https://IamJiyong.github.io"
source_url:         "https://github.com/IamJiyong/IamJiyong.github.io"

# Social Profiles
twitter_username:   
github_username:    
facebook_username:  
instagram_username:  dhwldyd
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

highlighter: rouge
paginate: 20
language: 'en-uk'

navigation: True
subscribers: True